import type { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    default: 'Next.js Project',
    template: '%s | Code',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
    {children}
      </body>
    </html>
  )
}
